apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
type: Opaque
data:
  JWT_SECRET: Q05BREFzc2lnbm1lbnQx
  SMTP_USER: amVmZnJleWxlZXByZzJAZ21haWwuY29t
  SMTP_PASSWORD: a2F6YXVteXJma3VxcW93bA==

  # Microservice-Specific Secrets
  ADMIN_DB_CONNECTION: YXZuYWRtaW46QVZOU19OLUo3VDFlZ2d1dmFGWDl6WEtkQHRjcChmYWxsc2FmZS1zZy1mYWxsc2FmZS1zZy5rLmFpdmVuY2xvdWQuY29tOjEzNzIyKS9GYWxsU2FmZV9BZG1pbkRC
  AUTH_DB_CONNECTION: YXZuYWRtaW46QVZOU19OLUo3VDFlZ2d1dmFGWDl6WEtkQHRjcChmYWxsc2FmZS1zZy1mYWxsc2FmZS1zZy5rLmFpdmVuY2xvdWQuY29tOjEzNzIyKS9GYWxsU2FmZV9BZG1pbkRC
  FES_DB_CONNECTION: YXZuYWRtaW46QVZOU19OLUo3VDFlZ2d1dmFGWDl6WEtkQHRjcChmYWxsc2FmZS1zZy1mYWxsc2FmZS1zZy5rLmFpdmVuY2xvdWQuY29tOjEzNzIyKS9GYWxsU2FmZV9GYWxsc0VmZmljYWN5U2NhbGVEQj9wYXJzZVRpbWU9dHJ1ZQ==
  SELF_DB_CONNECTION: YXZuYWRtaW46QVZOU19OLUo3VDFlZ2d1dmFGWDl6WEtkQHRjcChmYWxsc2FmZS1zZy1mYWxsc2FmZS1zZy5rLmFpdmVuY2xvdWQuY29tOjEzNzIyKS9GYWxsU2FmZV9TZWxmQXNzZXNzbWVudERCP3BhcnNlVGltZT10cnVl
  USER_DB_CONNECTION: YXZuYWRtaW46QVZOU19OLUo3VDFlZ2d1dmFGWDl6WEtkQHRjcChmYWxsc2FmZS1zZy1mYWxsc2FmZS1zZy5rLmFpdmVuY2xvdWQuY29tOjEzNzIyKS9GYWxsU2FmZV9Vc2VyREI=

  OPENAI_API_KEY: c2stcHJvai0teUtqVjViUkVFWmRLZ01MWHhSYmthTHJvSFkwTmdUSzZnWE5VWnc3R3BVcDVDSnB6eUh1RUVwOGJGZ3pQNWd0ODVRWEg2NEU2blQzQmxia0ZKb2cwVTVVS0lPWDUwaHBDZTM2RGdONGN6WDNqWEdGYy1haTdPOU1sMGttcUR1c0pNOVRuUFhVY3hMbk9POUpDVTdqamRIb1dUb0E=

  # AWS IoT Credentials for Self-Assessment Microservice
  AWS_IOT_ENDPOINT: YTJ3aGdrcGtzdzJiMXUtYXRzLmlvdC5hcC1zb3V0aGVhc3QtMS5hbWF6b25hd3MuY29t
  AWS_IOT_CLIENT_ID: c2VsZkFzc2Vzc21lbnRNaWNyb3NlcnZpY2U=
  AWS_IOT_CERT_FILE: YXdzSW9UQ29yZUNvbmZpZy9kZXZpY2UtY2VydGlmaWNhdGUucGVtLmNydA==
  AWS_IOT_KEY_FILE: YXdzSW9UQ29yZUNvbmZpZy9wcml2YXRlLnBlbS5rZXk=
  AWS_IOT_CA_FILE: YXdzSW9UQ29yZUNvbmZpZy9yb290LUNBLnBlbQ==
